services:
  backend:
    build: ./backend
    ports:
      - "5005:5005"
    env_file:
      - ./backend/.env
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # mount docker socket so backend can run docker containers

  frontend:
    build: ./frontend/my-app
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always